function createdFiles = create_training_models(projectRoot)
%CREATE_TRAINING_MODELS Build the aviation-controls Simulink training set.
%
%   createdFiles = CREATE_TRAINING_MODELS() locates the project from this
%   file, links every model to data/FCS_Data.sldd, creates the models in
%   models/, updates each diagram, and returns the absolute model paths.
%
%   createdFiles = CREATE_TRAINING_MODELS(projectRoot) uses the supplied
%   project root. The function is intentionally rerunnable: generated model
%   files are replaced, while files outside models/ are not modified.
%
%   Run initialize_training_data before this function. All numeric design
%   constants are illustrative training values stored in FCS_Data.sldd;
%   none represent production aircraft data.

arguments
    projectRoot (1,1) string = ""
end

if strlength(projectRoot) == 0
    projectRoot = string(fileparts(fileparts(mfilename('fullpath'))));
end
[status, attributes] = fileattrib(char(projectRoot));
if ~status
    error('TrainingModels:InvalidProjectRoot', ...
        'Could not resolve project root: %s', projectRoot);
end
projectRoot = string(attributes.Name);
modelsDir = fullfile(projectRoot, "models");
dataDir = fullfile(projectRoot, "data");
dictionaryPath = fullfile(dataDir, "FCS_Data.sldd");

if ~isfolder(modelsDir)
    error('TrainingModels:MissingModelsDirectory', ...
        'Expected models directory does not exist: %s', modelsDir);
end
if ~isfile(dictionaryPath)
    error('TrainingModels:MissingDictionary', ...
        ['FCS_Data.sldd was not found at %s. Run ' ...
         'initialize_training_data.m before create_training_models.m.'], ...
        dictionaryPath);
end

requiredEntries = [ ...
    "Sample_time", "q_limit_normal", "q_fallback_command", ...
    "pitch_Kp", "pitch_Ki", "pitch_rate_Kp", "pitch_rate_Ki", ...
    "controller_integrator_ic", ...
    "actuator_limit_deg", "actuator_filter_alpha", ...
    "aircraft_control_effectiveness", "aircraft_pitch_damping", ...
    "initial_q_rate", "initial_pitch_angle", ...
    "sensor_filter_alpha", "normal_mode_code", "FlightControlBus"];
verifyDictionaryEntries(dictionaryPath, requiredEntries);

pathWasAdded = false;
if ~contains(path, char(dataDir))
    addpath(char(dataDir));
    pathWasAdded = true;
end
pathCleanup = onCleanup(@()restoreTemporaryPaths( ...
    char(dataDir), pathWasAdded)); %#ok<NASGU>

load_system('simulink');

modelNames = [ ...
    "PitchRateLimiter", ...
    "AircraftFeedbackControlLoop", ...
    "AutopilotModeLogic", ...
    "SensorProcessingRef", ...
    "PitchControllerRef", ...
    "ActuatorCommandRef", ...
    "ReferencedFlightControlArchitecture", ...
    "PitchRateLimiter_Harness"];

try
    createPitchRateLimiter(modelsDir);
    createAircraftFeedbackControlLoop(modelsDir);
    createAutopilotModeLogic(modelsDir);

    % Referenced children must be saved and updated before the parent model
    % reference blocks are instantiated so their port interfaces are known.
    createSensorProcessingReference(modelsDir);
    createPitchControllerReference(modelsDir);
    createActuatorCommandReference(modelsDir);
    createReferencedArchitecture(modelsDir);
    createPitchRateLimiterHarness(modelsDir);

    for idx = 1:numel(modelNames)
        mdl = char(modelNames(idx));
        load_system(mdl);
        set_param(mdl, 'SimulationCommand', 'update');
        save_system(mdl);
    end
catch ME
    generated = modelNames(arrayfun(@(n)bdIsLoaded(char(n)), modelNames));
    for idx = 1:numel(generated)
        try
            close_system(char(generated(idx)), 0);
        catch
            % Preserve the original failure; cleanup errors are secondary.
        end
    end
    wrapper = MException('TrainingModels:BuildFailed', ...
        'Simulink training-model generation failed: %s', ME.message);
    throwAsCaller(addCause(wrapper, ME));
end

createdFiles = strings(numel(modelNames), 1);
for idx = 1:numel(modelNames)
    createdFiles(idx) = fullfile(modelsDir, modelNames(idx) + ".slx");
end

fprintf('Created and updated %d training models in:\n  %s\n', ...
    numel(createdFiles), modelsDir);
end


function createPitchRateLimiter(modelsDir)
mdl = 'PitchRateLimiter';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 4.0);
set_param(mdl, 'Description', [ ...
    'Illustrative 50 Hz pitch-rate command magnitude limiter. ' ...
    'Valid normal-mode inputs are clamped inclusively to plus/minus ' ...
    'q_limit_normal; invalid or non-normal inputs use q_fallback_command.']);

addTrainingBanner(mdl, [ ...
    'ILLUSTRATIVE TRAINING MODEL - NOT PRODUCTION AIRCRAFT DATA\n' ...
    'Pitch-rate MAGNITUDE limiter at 50 Hz. This is not a slew-rate limiter.']);

addInport(mdl, 'q_cmd_in', 1, [35 130 65 150], 'double', 'deg/s');
addInport(mdl, 'normal_mode', 2, [35 205 65 225], 'boolean', '1');
addInport(mdl, 'input_valid', 3, [35 270 65 290], 'boolean', '1');

logicPath = [mdl '/Pitch Rate Limiter Logic'];
add_block('simulink/Ports & Subsystems/Subsystem', logicPath, ...
    'Position', [190 105 440 315], ...
    'BackgroundColor', 'lightBlue', ...
    'ForegroundColor', 'blue');
set_param(logicPath, 'Description', [ ...
    'Inclusive magnitude clamp plus explicit validity/mode fallback. ' ...
    'limiter_active is true only while a valid command exceeds a limit.']);
buildPitchLimiterSubsystem(logicPath);

addOutport(mdl, 'q_cmd_out', 1, [575 145 605 165], 'double', 'deg/s');
addOutport(mdl, 'limiter_active', 2, [575 245 605 265], 'boolean', '1');

addNamedLine(mdl, 'q_cmd_in/1', 'Pitch Rate Limiter Logic/1', ...
    'q_cmd_in_deg_s', true);
addNamedLine(mdl, 'normal_mode/1', 'Pitch Rate Limiter Logic/2', ...
    'normal_mode', true);
addNamedLine(mdl, 'input_valid/1', 'Pitch Rate Limiter Logic/3', ...
    'input_valid', true);
addNamedLine(mdl, 'Pitch Rate Limiter Logic/1', 'q_cmd_out/1', ...
    'q_cmd_out_deg_s', true);
addNamedLine(mdl, 'Pitch Rate Limiter Logic/2', 'limiter_active/1', ...
    'limiter_active', true);

saveGeneratedModel(mdl, modelsDir);
end


function buildPitchLimiterSubsystem(sys)
Simulink.SubSystem.deleteContents(sys);
addInport(sys, 'q_cmd_in', 1, [25 80 55 100], 'double', 'deg/s');
addInport(sys, 'normal_mode', 2, [25 235 55 255], 'boolean', '1');
addInport(sys, 'input_valid', 3, [25 290 55 310], 'boolean', '1');

validPath = [sys '/Normal AND Valid'];
add_block('simulink/Logic and Bit Operations/Logical Operator', validPath, ...
    'Operator', 'AND', 'Inputs', '2', ...
    'Position', [135 240 175 300], ...
    'BackgroundColor', 'yellow');

satPath = [sys '/Magnitude Clamp'];
add_block('simulink/Discontinuities/Saturation', satPath, ...
    'UpperLimit', 'q_limit_normal', ...
    'LowerLimit', '-q_limit_normal', ...
    'Position', [155 65 245 115], ...
    'BackgroundColor', 'lightBlue');
set_param(satPath, 'Description', [ ...
    'Inclusive command magnitude clamp. This block limits magnitude, ' ...
    'not the rate of change of the signal.']);

fallbackPath = [sys '/Training Fallback Command'];
add_block('simulink/Sources/Constant', fallbackPath, ...
    'Value', 'q_fallback_command', ...
    'OutDataTypeStr', 'double', ...
    'SampleTime', 'Sample_time', ...
    'Position', [160 155 245 185], ...
    'BackgroundColor', 'yellow');
set_param(fallbackPath, 'Description', ...
    'Documented training fallback: zero pitch-rate command.');

switchPath = [sys '/Select Valid Command'];
add_block('simulink/Signal Routing/Switch', switchPath, ...
    'Criteria', 'u2 ~= 0', ...
    'Threshold', '0.5', ...
    'Position', [320 80 375 195], ...
    'BackgroundColor', 'yellow');

abovePath = [sys '/Above Positive Limit'];
add_block('simulink/Logic and Bit Operations/Relational Operator', abovePath, ...
    'Operator', '>', ...
    'Position', [155 360 195 390], ...
    'BackgroundColor', 'yellow');
posLimitPath = [sys '/Positive Limit'];
add_block('simulink/Sources/Constant', posLimitPath, ...
    'Value', 'q_limit_normal', ...
    'OutDataTypeStr', 'double', ...
    'SampleTime', 'Sample_time', ...
    'Position', [80 405 135 435], ...
    'BackgroundColor', 'yellow');

belowPath = [sys '/Below Negative Limit'];
add_block('simulink/Logic and Bit Operations/Relational Operator', belowPath, ...
    'Operator', '<', ...
    'Position', [155 475 195 505], ...
    'BackgroundColor', 'yellow');
negLimitPath = [sys '/Negative Limit'];
add_block('simulink/Sources/Constant', negLimitPath, ...
    'Value', '-q_limit_normal', ...
    'OutDataTypeStr', 'double', ...
    'SampleTime', 'Sample_time', ...
    'Position', [80 520 135 550], ...
    'BackgroundColor', 'yellow');

outsidePath = [sys '/Outside Inclusive Range'];
add_block('simulink/Logic and Bit Operations/Logical Operator', outsidePath, ...
    'Operator', 'OR', 'Inputs', '2', ...
    'Position', [250 405 290 465], ...
    'BackgroundColor', 'yellow');
activePath = [sys '/Valid Clamp Active'];
add_block('simulink/Logic and Bit Operations/Logical Operator', activePath, ...
    'Operator', 'AND', 'Inputs', '2', ...
    'Position', [350 375 395 435], ...
    'BackgroundColor', 'yellow');

addOutport(sys, 'q_cmd_out', 1, [465 120 495 140], 'double', 'deg/s');
addOutport(sys, 'limiter_active', 2, [465 395 495 415], 'boolean', '1');

addNamedLine(sys, 'normal_mode/1', 'Normal AND Valid/1', 'normal_mode', false);
addNamedLine(sys, 'input_valid/1', 'Normal AND Valid/2', 'input_valid', false);
addNamedLine(sys, 'q_cmd_in/1', 'Magnitude Clamp/1', 'q_cmd_raw_deg_s', false);
addNamedLine(sys, 'Magnitude Clamp/1', 'Select Valid Command/1', ...
    'q_cmd_clamped_deg_s', false);
addNamedLine(sys, 'Normal AND Valid/1', 'Select Valid Command/2', ...
    'normal_and_valid', false);
addNamedLine(sys, 'Training Fallback Command/1', 'Select Valid Command/3', ...
    'fallback_deg_s', false);
addNamedLine(sys, 'Select Valid Command/1', 'q_cmd_out/1', ...
    'q_cmd_selected_deg_s', false);

addNamedLine(sys, 'q_cmd_in/1', 'Above Positive Limit/1', '', false);
addNamedLine(sys, 'Positive Limit/1', 'Above Positive Limit/2', '', false);
addNamedLine(sys, 'q_cmd_in/1', 'Below Negative Limit/1', '', false);
addNamedLine(sys, 'Negative Limit/1', 'Below Negative Limit/2', '', false);
addNamedLine(sys, 'Above Positive Limit/1', 'Outside Inclusive Range/1', ...
    'above_positive_limit', false);
addNamedLine(sys, 'Below Negative Limit/1', 'Outside Inclusive Range/2', ...
    'below_negative_limit', false);
addNamedLine(sys, 'Outside Inclusive Range/1', 'Valid Clamp Active/1', ...
    'outside_limit', false);
addNamedLine(sys, 'Normal AND Valid/1', 'Valid Clamp Active/2', '', false);
addNamedLine(sys, 'Valid Clamp Active/1', 'limiter_active/1', ...
    'limiter_active', false);

addTrainingNote(sys, [30 585 500 635], [ ...
    'At exactly +/-q_limit_normal the output equals the input and ' ...
    'limiter_active is false. Invalid/non-normal fallback does not assert ' ...
    'the magnitude-limiter flag.']);
end


function createAircraftFeedbackControlLoop(modelsDir)
mdl = 'AircraftFeedbackControlLoop';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 12.0);
set_param(mdl, 'Description', [ ...
    'Illustrative 50 Hz closed-loop longitudinal training plant. ' ...
    'The parameters are deliberately simplified and are not aircraft data.']);
addTrainingBanner(mdl, [ ...
    'ILLUSTRATIVE CLOSED-LOOP TRAINING MODEL - NOT PRODUCTION AIRCRAFT DATA\n' ...
    'Pilot/guidance command -> PI control -> actuator -> simplified plant -> sensor feedback']);

addInport(mdl, 'pitch_cmd_deg', 1, [30 150 60 170], 'double', 'deg');
addInport(mdl, 'disturbance_deg_s2', 2, [30 365 60 385], 'double', 'deg/s^2');

sumPath = [mdl '/Tracking Error'];
add_block('simulink/Math Operations/Sum', sumPath, ...
    'Inputs', '+-', ...
    'IconShape', 'round', ...
    'Position', [145 135 180 175], ...
    'BackgroundColor', 'yellow');

controllerPath = [mdl '/Pitch Controller PI'];
add_block('simulink/Ports & Subsystems/Subsystem', controllerPath, ...
    'Position', [240 115 385 195], ...
    'BackgroundColor', 'lightBlue');
buildPIControllerSubsystem(controllerPath, 'error_deg', 'actuator_demand_deg');

satPath = [mdl '/Actuator Command Saturation'];
add_block('simulink/Discontinuities/Saturation', satPath, ...
    'UpperLimit', 'actuator_limit_deg', ...
    'LowerLimit', '-actuator_limit_deg', ...
    'Position', [435 130 510 180], ...
    'BackgroundColor', 'yellow');

actuatorPath = [mdl '/Actuator Dynamics'];
add_block('simulink/Ports & Subsystems/Subsystem', actuatorPath, ...
    'Position', [565 115 700 195], ...
    'BackgroundColor', 'lightBlue');
buildActuatorDynamicsSubsystem(actuatorPath);

plantPath = [mdl '/Simplified Longitudinal Aircraft Dynamics'];
add_block('simulink/Ports & Subsystems/Subsystem', plantPath, ...
    'Position', [765 100 960 230], ...
    'BackgroundColor', 'lightBlue');
buildLongitudinalPlantSubsystem(plantPath);

sensorPath = [mdl '/Sensor Processing Lag'];
add_block('simulink/Ports & Subsystems/Subsystem', sensorPath, ...
    'Position', [610 285 765 355], ...
    'BackgroundColor', 'lightBlue');
buildSensorLagSubsystem(sensorPath);

addOutport(mdl, 'pitch_response_deg', 1, [1065 115 1095 135], 'double', 'deg');
addOutport(mdl, 'q_rate_deg_s', 2, [1065 205 1095 225], 'double', 'deg/s');
addOutport(mdl, 'actuator_cmd_deg', 3, [1065 285 1095 305], 'double', 'deg');
addOutport(mdl, 'tracking_error_deg', 4, [1065 365 1095 385], 'double', 'deg');

addNamedLine(mdl, 'pitch_cmd_deg/1', 'Tracking Error/1', ...
    'command', true);
addNamedLine(mdl, 'Tracking Error/1', 'Pitch Controller PI/1', ...
    'error', true);
addNamedLine(mdl, 'Pitch Controller PI/1', 'Actuator Command Saturation/1', ...
    'controller_demand', true);
addNamedLine(mdl, 'Actuator Command Saturation/1', 'Actuator Dynamics/1', ...
    'actuator_command_limited', true);
addNamedLine(mdl, 'Actuator Dynamics/1', ...
    'Simplified Longitudinal Aircraft Dynamics/1', 'actuator', true);
addNamedLine(mdl, 'disturbance_deg_s2/1', ...
    'Simplified Longitudinal Aircraft Dynamics/2', 'disturbance', true);
addNamedLine(mdl, 'Simplified Longitudinal Aircraft Dynamics/1', ...
    'pitch_response_deg/1', 'response', true);
addNamedLine(mdl, 'Simplified Longitudinal Aircraft Dynamics/1', ...
    'Sensor Processing Lag/1', '', false);
addNamedLine(mdl, 'Sensor Processing Lag/1', 'Tracking Error/2', ...
    'measured_pitch', true);
addNamedLine(mdl, 'Simplified Longitudinal Aircraft Dynamics/2', ...
    'q_rate_deg_s/1', 'q_rate', true);
addNamedLine(mdl, 'Actuator Dynamics/1', 'actuator_cmd_deg/1', '', false);
addNamedLine(mdl, 'Tracking Error/1', 'tracking_error_deg/1', '', false);

addTrainingNote(mdl, [255 430 900 485], [ ...
    'Training plant: control effectiveness + pitch-rate damping + two ' ...
    'discrete integrators. It demonstrates feedback structure and logged ' ...
    'evidence; it is not an identified or certifiable aircraft model.']);

saveGeneratedModel(mdl, modelsDir);
end


function buildPIControllerSubsystem(sys, inputName, outputName)
Simulink.SubSystem.deleteContents(sys);
isRateController = contains(char(inputName), 'q_error');
inputUnit = 'deg';
proportionalGain = 'pitch_Kp';
integralGain = 'pitch_Ki';
if isRateController
    inputUnit = 'deg/s';
    proportionalGain = 'pitch_rate_Kp';
    integralGain = 'pitch_rate_Ki';
end
addInport(sys, inputName, 1, [25 115 55 135], 'double', inputUnit);

pPath = [sys '/Proportional Gain'];
add_block('simulink/Math Operations/Gain', pPath, ...
    'Gain', proportionalGain, ...
    'Position', [115 70 180 110], ...
    'BackgroundColor', 'lightBlue');
iGainPath = [sys '/Integral Gain'];
add_block('simulink/Math Operations/Gain', iGainPath, ...
    'Gain', integralGain, ...
    'Position', [115 155 180 195], ...
    'BackgroundColor', 'lightBlue');
iPath = [sys '/Discrete Integrator'];
add_block('simulink/Discrete/Discrete-Time Integrator', iPath, ...
    'gainval', '1', ...
    'SampleTime', 'Sample_time', ...
    'InitialCondition', 'controller_integrator_ic', ...
    'IntegratorMethod', 'Forward Euler', ...
    'Position', [230 150 295 200], ...
    'BackgroundColor', 'lightBlue');
sumPath = [sys '/P plus I'];
add_block('simulink/Math Operations/Sum', sumPath, ...
    'Inputs', '++', ...
    'Position', [350 95 385 165], ...
    'BackgroundColor', 'yellow');
addOutport(sys, outputName, 1, [450 120 480 140], 'double', 'deg');

addNamedLine(sys, [char(inputName) '/1'], 'Proportional Gain/1', ...
    'tracking_error_deg', false);
addNamedLine(sys, [char(inputName) '/1'], 'Integral Gain/1', '', false);
addNamedLine(sys, 'Proportional Gain/1', 'P plus I/1', 'proportional_term', false);
addNamedLine(sys, 'Integral Gain/1', 'Discrete Integrator/1', '', false);
addNamedLine(sys, 'Discrete Integrator/1', 'P plus I/2', 'integral_term', false);
addNamedLine(sys, 'P plus I/1', [char(outputName) '/1'], ...
    'actuator_demand_deg', false);
addTrainingNote(sys, [40 245 455 285], ...
    'Dimensionally consistent PI gains and deterministic initial condition are controlled in FCS_Data.sldd.');
end


function buildActuatorDynamicsSubsystem(sys)
Simulink.SubSystem.deleteContents(sys);
addInport(sys, 'actuator_cmd_in', 1, [25 90 55 110], 'double', 'deg');
lagPath = [sys '/First Order Discrete Lag'];
add_block('simulink/Discrete/Discrete Transfer Fcn', lagPath, ...
    'Numerator', '(1-actuator_filter_alpha)', ...
    'Denominator', '[1 -actuator_filter_alpha]', ...
    'InitialStates', '0', ...
    'SampleTime', 'Sample_time', ...
    'Position', [135 70 265 125], ...
    'BackgroundColor', 'lightBlue');
addOutport(sys, 'actuator_position', 1, [350 90 380 110], 'double', 'deg');
addNamedLine(sys, 'actuator_cmd_in/1', 'First Order Discrete Lag/1', ...
    'actuator_command_deg', false);
addNamedLine(sys, 'First Order Discrete Lag/1', 'actuator_position/1', ...
    'actuator_position_deg', false);
addTrainingNote(sys, [55 170 350 215], ...
    'Illustrative first-order digital actuator response; alpha is dictionary controlled.');
end


function buildLongitudinalPlantSubsystem(sys)
Simulink.SubSystem.deleteContents(sys);
addInport(sys, 'actuator_position_deg', 1, [25 95 55 115], 'double', 'deg');
addInport(sys, 'disturbance_deg_s2', 2, [25 265 55 285], 'double', 'deg/s^2');

controlPath = [sys '/Control Effectiveness'];
add_block('simulink/Math Operations/Gain', controlPath, ...
    'Gain', 'aircraft_control_effectiveness', ...
    'Position', [115 75 205 125], ...
    'BackgroundColor', 'lightBlue');
dampingPath = [sys '/Pitch Rate Damping'];
add_block('simulink/Math Operations/Gain', dampingPath, ...
    'Gain', '-aircraft_pitch_damping', ...
    'Position', [115 175 205 225], ...
    'BackgroundColor', 'lightBlue');
accelPath = [sys '/Pitch Acceleration Sum'];
add_block('simulink/Math Operations/Sum', accelPath, ...
    'Inputs', '+++', ...
    'Position', [270 115 305 245], ...
    'BackgroundColor', 'yellow');
qIntPath = [sys '/Integrate Pitch Rate'];
add_block('simulink/Discrete/Discrete-Time Integrator', qIntPath, ...
    'gainval', '1', ...
    'SampleTime', 'Sample_time', ...
    'InitialCondition', 'initial_q_rate', ...
    'IntegratorMethod', 'Forward Euler', ...
    'Position', [370 135 450 185], ...
    'BackgroundColor', 'lightBlue');
pitchIntPath = [sys '/Integrate Pitch Angle'];
add_block('simulink/Discrete/Discrete-Time Integrator', pitchIntPath, ...
    'gainval', '1', ...
    'SampleTime', 'Sample_time', ...
    'InitialCondition', 'initial_pitch_angle', ...
    'IntegratorMethod', 'Forward Euler', ...
    'Position', [525 135 605 185], ...
    'BackgroundColor', 'lightBlue');
addOutport(sys, 'pitch_angle_deg', 1, [700 140 730 160], 'double', 'deg');
addOutport(sys, 'q_rate_deg_s', 2, [700 225 730 245], 'double', 'deg/s');

addNamedLine(sys, 'actuator_position_deg/1', 'Control Effectiveness/1', ...
    'actuator_position_deg', false);
addNamedLine(sys, 'Control Effectiveness/1', 'Pitch Acceleration Sum/1', ...
    'control_acceleration_deg_s2', false);
addNamedLine(sys, 'Pitch Rate Damping/1', 'Pitch Acceleration Sum/2', ...
    'damping_acceleration_deg_s2', false);
addNamedLine(sys, 'disturbance_deg_s2/1', 'Pitch Acceleration Sum/3', ...
    'disturbance_deg_s2', false);
addNamedLine(sys, 'Pitch Acceleration Sum/1', 'Integrate Pitch Rate/1', ...
    'q_dot_deg_s2', false);
addNamedLine(sys, 'Integrate Pitch Rate/1', 'Integrate Pitch Angle/1', ...
    'q_rate_deg_s', false);
addNamedLine(sys, 'Integrate Pitch Rate/1', 'Pitch Rate Damping/1', '', false);
addNamedLine(sys, 'Integrate Pitch Rate/1', 'q_rate_deg_s/1', '', false);
addNamedLine(sys, 'Integrate Pitch Angle/1', 'pitch_angle_deg/1', ...
    'pitch_angle_deg', false);
addTrainingNote(sys, [90 330 650 380], [ ...
    'Illustrative longitudinal response only: q_dot = control effect - ' ...
    'q damping + disturbance; integrate q and pitch at Sample_time.']);
end


function buildSensorLagSubsystem(sys)
Simulink.SubSystem.deleteContents(sys);
addInport(sys, 'pitch_angle_raw', 1, [25 80 55 100], 'double', 'deg');
filterPath = [sys '/Discrete Sensor Filter'];
add_block('simulink/Discrete/Discrete Transfer Fcn', filterPath, ...
    'Numerator', '(1-sensor_filter_alpha)', ...
    'Denominator', '[1 -sensor_filter_alpha]', ...
    'InitialStates', '0', ...
    'SampleTime', 'Sample_time', ...
    'Position', [130 65 265 120], ...
    'BackgroundColor', 'lightBlue');
addOutport(sys, 'pitch_angle_measured', 1, [355 80 385 100], 'double', 'deg');
addNamedLine(sys, 'pitch_angle_raw/1', 'Discrete Sensor Filter/1', ...
    'pitch_angle_raw_deg', false);
addNamedLine(sys, 'Discrete Sensor Filter/1', 'pitch_angle_measured/1', ...
    'pitch_angle_measured_deg', false);
addTrainingNote(sys, [55 165 355 205], ...
    'Sensor lag is a controlled first-order discrete filter at 50 Hz.');
end


function createAutopilotModeLogic(modelsDir)
mdl = 'AutopilotModeLogic';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 8.0);
set_param(mdl, 'Description', [ ...
    'Illustrative autopilot mode-management training logic with OFF, ' ...
    'ARMED, ENGAGED, and DEGRADED states.']);
addTrainingBanner(mdl, [ ...
    'ILLUSTRATIVE AUTOPILOT MODE LOGIC - NOT PRODUCTION AIRCRAFT LOGIC\n' ...
    'Transitions expose engagement, validity, fault, disengagement, and reset guards.']);

inputs = { ...
    'engage_request', 'sensor_valid', 'engage_success', ...
    'fault_detected', 'disengage_request', 'reset_request'};
for idx = 1:numel(inputs)
    y = 90 + (idx-1)*55;
    addInport(mdl, inputs{idx}, idx, [30 y 60 y+20], 'boolean', '1');
end

chartPath = [mdl '/Autopilot Mode Logic'];
hasStateflow = ~isempty(ver('stateflow')) && license('test', 'Stateflow');
if hasStateflow
    buildStateflowModeChart(mdl, chartPath);
    implementationText = 'Stateflow implementation: OFF / ARMED / ENGAGED / DEGRADED';
else
    add_block('simulink/Ports & Subsystems/Subsystem', chartPath, ...
        'Position', [285 85 590 405], ...
        'BackgroundColor', 'yellow');
    buildSimulinkModeFallback(chartPath);
    implementationText = [ ...
        'Stateflow license unavailable: explicit discrete Simulink fallback ' ...
        'implements OFF / ARMED / ENGAGED / DEGRADED.'];
end

addOutport(mdl, 'mode_code', 1, [720 165 750 185], 'uint8', '1');
addOutport(mdl, 'control_enabled', 2, [720 295 750 315], 'boolean', '1');
for idx = 1:numel(inputs)
    addNamedLine(mdl, sprintf('%s/1', inputs{idx}), ...
        sprintf('Autopilot Mode Logic/%d', idx), inputs{idx}, true);
end
addNamedLine(mdl, 'Autopilot Mode Logic/1', 'mode_code/1', 'mode_code', true);
addNamedLine(mdl, 'Autopilot Mode Logic/2', 'control_enabled/1', ...
    'control_enabled', true);
addTrainingNote(mdl, [185 455 635 505], implementationText);

saveGeneratedModel(mdl, modelsDir);
end


function buildStateflowModeChart(mdl, chartPath)
load_system('sflib');
add_block('sflib/Chart', chartPath, ...
    'Position', [285 85 590 405], ...
    'BackgroundColor', 'lightBlue');

rt = sfroot;
sfModel = rt.find('-isa', 'Simulink.BlockDiagram', 'Name', mdl);
if isempty(sfModel)
    error('TrainingModels:StateflowModelNotFound', ...
        'Stateflow could not locate model %s after adding its chart.', mdl);
end
chart = sfModel.find('-isa', 'Stateflow.Chart', 'Name', 'Autopilot Mode Logic');
if isempty(chart)
    error('TrainingModels:StateflowChartNotFound', ...
        'Stateflow chart object was not created at %s.', chartPath);
end
chart = chart(1);
chart.Description = [ ...
    'Illustrative training mode state machine. mode_code mapping: ' ...
    'OFF=0, ARMED=1, ENGAGED=2, DEGRADED=3.'];
chart.PaperOrientation = 'landscape';
chart.PaperType = 'A3';

inputNames = { ...
    'engage_request', 'sensor_valid', 'engage_success', ...
    'fault_detected', 'disengage_request', 'reset_request'};
for idx = 1:numel(inputNames)
    d = Stateflow.Data(chart);
    d.Name = inputNames{idx};
    d.Scope = 'Input';
    d.Port = idx;
    d.Props.Type.Method = 'Built-in';
    d.Props.Type.Primitive = 'boolean';
end

modeData = Stateflow.Data(chart);
modeData.Name = 'mode_code';
modeData.Scope = 'Output';
modeData.Port = 1;
modeData.Props.Type.Method = 'Built-in';
modeData.Props.Type.Primitive = 'uint8';

enabledData = Stateflow.Data(chart);
enabledData.Name = 'control_enabled';
enabledData.Scope = 'Output';
enabledData.Port = 2;
enabledData.Props.Type.Method = 'Built-in';
enabledData.Props.Type.Primitive = 'boolean';

off = makeState(chart, 'OFF', [40 60 180 100], 0, false);
armed = makeState(chart, 'ARMED', [480 60 190 100], 1, false);
engaged = makeState(chart, 'ENGAGED', [480 360 190 100], 2, true);
degraded = makeState(chart, 'DEGRADED', [40 360 200 100], 3, false);

defaultTransition = Stateflow.Transition(chart);
defaultTransition.Destination = off;
defaultTransition.DestinationOClock = 0;
defaultTransition.SourceEndpoint = [130 10];
defaultTransition.MidPoint = [130 35];

t = makeTransition(chart, off, armed, ...
    '[engage_request && sensor_valid]', 3, 9);
setTransitionGeometry(t, [350 110], [260 82 210 18]);
t = makeTransition(chart, armed, engaged, ...
    '[engage_success && sensor_valid]', 6, 0);
setTransitionGeometry(t, [575 260], [590 245 220 18]);
t = makeTransition(chart, armed, degraded, ...
    '[fault_detected || !sensor_valid]', 9, 3);
setTransitionGeometry(t, [350 250], [255 225 220 18]);
t = makeTransition(chart, engaged, degraded, ...
    '[fault_detected || !sensor_valid]', 9, 3);
setTransitionGeometry(t, [360 410], [255 430 220 18]);
t = makeTransition(chart, armed, off, '[disengage_request]', 0, 0);
setTransitionGeometry(t, [350 20], [285 8 160 18]);
t = makeTransition(chart, engaged, off, '[disengage_request]', 3, 0);
setTransitionGeometry(t, [760 230], [680 210 160 18]);
t = makeTransition(chart, degraded, off, ...
    '[reset_request || disengage_request]', 0, 6);
setTransitionGeometry(t, [140 260], [10 245 235 18]);
end


function state = makeState(chart, name, position, code, enabled)
state = Stateflow.State(chart);
state.Name = name;
state.Position = position;
state.LabelString = sprintf([ ...
    '%s\nentry:\n  mode_code = uint8(%d);\n  control_enabled = %s;'], ...
    name, code, lower(mat2str(enabled)));
state.FontSize = 11;
end


function transition = makeTransition(chart, source, destination, label, sourceClock, destinationClock)
transition = Stateflow.Transition(chart);
transition.Source = source;
transition.Destination = destination;
transition.LabelString = label;
transition.SourceOClock = sourceClock;
transition.DestinationOClock = destinationClock;
transition.FontSize = 10;
end


function setTransitionGeometry(transition, midpoint, labelPosition)
transition.MidPoint = midpoint;
transition.LabelPosition = labelPosition;
end


function buildSimulinkModeFallback(sys)
Simulink.SubSystem.deleteContents(sys);
inputNames = { ...
    'engage_request', 'sensor_valid', 'engage_success', ...
    'fault_detected', 'disengage_request', 'reset_request'};
for idx = 1:numel(inputNames)
    y = 45 + (idx-1)*45;
    addInport(sys, inputNames{idx}, idx, [20 y 50 y+20], 'boolean', '1');
end

stateMemory = [sys '/Previous Mode'];
add_block('simulink/Discrete/Unit Delay', stateMemory, ...
    'InitialCondition', 'uint8(0)', ...
    'SampleTime', 'Sample_time', ...
    'OutDataTypeStr', 'uint8', ...
    'Position', [565 145 620 185], ...
    'BackgroundColor', 'lightBlue');

% Current-state decodes.
stateNames = {'Is OFF', 'Is ARMED', 'Is ENGAGED'};
stateCodes = {'uint8(0)', 'uint8(1)', 'uint8(2)'};
for idx = 1:3
    path = [sys '/' stateNames{idx}];
    add_block('simulink/Logic and Bit Operations/Compare To Constant', path, ...
        'relop', '==', 'const', stateCodes{idx}, ...
        'Position', [100 315+(idx-1)*45 175 340+(idx-1)*45], ...
        'BackgroundColor', 'yellow');
    addNamedLine(sys, 'Previous Mode/1', [stateNames{idx} '/1'], '', false);
end

validEngage = [sys '/Request AND Valid'];
add_block('simulink/Logic and Bit Operations/Logical Operator', validEngage, ...
    'Operator', 'AND', 'Inputs', '2', ...
    'Position', [105 45 150 90], 'BackgroundColor', 'yellow');
armCondition = [sys '/OFF To ARMED'];
add_block('simulink/Logic and Bit Operations/Logical Operator', armCondition, ...
    'Operator', 'AND', 'Inputs', '2', ...
    'Position', [215 50 260 95], 'BackgroundColor', 'yellow');
engageCondition = [sys '/ARMED To ENGAGED'];
add_block('simulink/Logic and Bit Operations/Logical Operator', engageCondition, ...
    'Operator', 'AND', 'Inputs', '3', ...
    'Position', [215 125 260 180], 'BackgroundColor', 'yellow');
invalidPath = [sys '/Invalid OR Fault'];
add_block('simulink/Logic and Bit Operations/Logical Operator', invalidPath, ...
    'Operator', 'OR', 'Inputs', '2', ...
    'Position', [215 220 260 270], 'BackgroundColor', 'yellow');
notValidPath = [sys '/NOT Sensor Valid'];
add_block('simulink/Logic and Bit Operations/Logical Operator', notValidPath, ...
    'Operator', 'NOT', 'Inputs', '1', ...
    'Position', [115 225 155 255], 'BackgroundColor', 'yellow');
resetPath = [sys '/Reset OR Disengage'];
add_block('simulink/Logic and Bit Operations/Logical Operator', resetPath, ...
    'Operator', 'OR', 'Inputs', '2', ...
    'Position', [215 285 260 335], 'BackgroundColor', 'yellow');

% Priority chain: hold -> arm -> engage -> degrade -> reset/off.
constants = { ...
    'ARMED Code', 'uint8(1)', [315 55 365 80]; ...
    'ENGAGED Code', 'uint8(2)', [315 125 365 150]; ...
    'DEGRADED Code', 'uint8(3)', [315 220 365 245]; ...
    'OFF Code', 'uint8(0)', [315 305 365 330]};
for idx = 1:size(constants,1)
    add_block('simulink/Sources/Constant', [sys '/' constants{idx,1}], ...
        'Value', constants{idx,2}, 'OutDataTypeStr', 'uint8', ...
        'SampleTime', 'Sample_time', 'Position', constants{idx,3}, ...
        'BackgroundColor', 'yellow');
end
switchNames = {'Apply Arm', 'Apply Engage', 'Apply Degrade', 'Apply Reset'};
switchY = [45 115 205 290];
for idx = 1:4
    add_block('simulink/Signal Routing/Switch', [sys '/' switchNames{idx}], ...
        'Criteria', 'u2 ~= 0', 'Threshold', '0.5', ...
        'Position', [410 switchY(idx) 455 switchY(idx)+60], ...
        'BackgroundColor', 'yellow');
end

addNamedLine(sys, 'engage_request/1', 'Request AND Valid/1', '', false);
addNamedLine(sys, 'sensor_valid/1', 'Request AND Valid/2', '', false);
addNamedLine(sys, 'Request AND Valid/1', 'OFF To ARMED/1', '', false);
addNamedLine(sys, 'Is OFF/1', 'OFF To ARMED/2', '', false);
addNamedLine(sys, 'engage_success/1', 'ARMED To ENGAGED/1', '', false);
addNamedLine(sys, 'sensor_valid/1', 'ARMED To ENGAGED/2', '', false);
addNamedLine(sys, 'Is ARMED/1', 'ARMED To ENGAGED/3', '', false);
addNamedLine(sys, 'sensor_valid/1', 'NOT Sensor Valid/1', '', false);
addNamedLine(sys, 'fault_detected/1', 'Invalid OR Fault/1', '', false);
addNamedLine(sys, 'NOT Sensor Valid/1', 'Invalid OR Fault/2', '', false);
addNamedLine(sys, 'reset_request/1', 'Reset OR Disengage/1', '', false);
addNamedLine(sys, 'disengage_request/1', 'Reset OR Disengage/2', '', false);

addNamedLine(sys, 'ARMED Code/1', 'Apply Arm/1', '', false);
addNamedLine(sys, 'OFF To ARMED/1', 'Apply Arm/2', '', false);
addNamedLine(sys, 'Previous Mode/1', 'Apply Arm/3', '', false);
addNamedLine(sys, 'ENGAGED Code/1', 'Apply Engage/1', '', false);
addNamedLine(sys, 'ARMED To ENGAGED/1', 'Apply Engage/2', '', false);
addNamedLine(sys, 'Apply Arm/1', 'Apply Engage/3', '', false);
addNamedLine(sys, 'DEGRADED Code/1', 'Apply Degrade/1', '', false);
addNamedLine(sys, 'Invalid OR Fault/1', 'Apply Degrade/2', '', false);
addNamedLine(sys, 'Apply Engage/1', 'Apply Degrade/3', '', false);
addNamedLine(sys, 'OFF Code/1', 'Apply Reset/1', '', false);
addNamedLine(sys, 'Reset OR Disengage/1', 'Apply Reset/2', '', false);
addNamedLine(sys, 'Apply Degrade/1', 'Apply Reset/3', '', false);
addNamedLine(sys, 'Apply Reset/1', 'Previous Mode/1', 'next_mode', false);

enabledPath = [sys '/Mode Is ENGAGED'];
add_block('simulink/Logic and Bit Operations/Compare To Constant', enabledPath, ...
    'relop', '==', 'const', 'uint8(2)', ...
    'Position', [650 225 735 255], ...
    'BackgroundColor', 'yellow');
addOutport(sys, 'mode_code', 1, [785 155 815 175], 'uint8', '1');
addOutport(sys, 'control_enabled', 2, [785 230 815 250], 'boolean', '1');
addNamedLine(sys, 'Previous Mode/1', 'mode_code/1', 'mode_code', false);
addNamedLine(sys, 'Previous Mode/1', 'Mode Is ENGAGED/1', '', false);
addNamedLine(sys, 'Mode Is ENGAGED/1', 'control_enabled/1', ...
    'control_enabled', false);
end


function createSensorProcessingReference(modelsDir)
mdl = 'SensorProcessingRef';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 2.0);
set_param(mdl, 'Description', ...
    'Referenced sensor-processing component with a FlightControlBus interface.');
addTrainingBanner(mdl, ...
    'REFERENCED TRAINING COMPONENT - typed FlightControlBus in/out; q-rate filtering at 50 Hz');

addBusInport(mdl, 'sensor_bus_in', 1, [30 175 60 195]);
selectorPath = [mdl '/Select Bus Elements'];
add_block('simulink/Signal Routing/Bus Selector', selectorPath, ...
    'OutputSignals', 'q_rate,pitch_angle,mach,air_data_valid,mode', ...
    'Position', [130 80 180 300], ...
    'BackgroundColor', 'lightBlue');
qFilterPath = [mdl '/Q Rate Sensor Filter'];
add_block('simulink/Discrete/Discrete Transfer Fcn', qFilterPath, ...
    'Numerator', '(1-sensor_filter_alpha)', ...
    'Denominator', '[1 -sensor_filter_alpha]', ...
    'InitialStates', '0', ...
    'SampleTime', 'Sample_time', ...
    'Position', [250 75 375 125], ...
    'BackgroundColor', 'lightBlue');
creatorPath = [mdl '/Create Processed Bus'];
add_block('simulink/Signal Routing/Bus Creator', creatorPath, ...
    'Inputs', '5', ...
    'OutDataTypeStr', 'Bus: FlightControlBus', ...
    'Position', [470 80 520 300], ...
    'BackgroundColor', 'lightBlue');
addBusOutport(mdl, 'processed_bus_out', 1, [625 175 655 195]);

addNamedLine(mdl, 'sensor_bus_in/1', 'Select Bus Elements/1', ...
    'raw_flight_control_bus', true);
addNamedLine(mdl, 'Select Bus Elements/1', 'Q Rate Sensor Filter/1', ...
    'q_rate_raw', false);
addNamedLine(mdl, 'Q Rate Sensor Filter/1', 'Create Processed Bus/1', ...
    'q_rate', false);
addNamedLine(mdl, 'Select Bus Elements/2', 'Create Processed Bus/2', ...
    'pitch_angle', false);
addNamedLine(mdl, 'Select Bus Elements/3', 'Create Processed Bus/3', ...
    'mach', false);
addNamedLine(mdl, 'Select Bus Elements/4', 'Create Processed Bus/4', ...
    'air_data_valid', false);
addNamedLine(mdl, 'Select Bus Elements/5', 'Create Processed Bus/5', ...
    'mode', false);
addNamedLine(mdl, 'Create Processed Bus/1', 'processed_bus_out/1', ...
    'processed_flight_control_bus', true);

saveGeneratedModel(mdl, modelsDir);
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);
end


function createPitchControllerReference(modelsDir)
mdl = 'PitchControllerRef';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 2.0);
set_param(mdl, 'Description', ...
    'Referenced 50 Hz pitch-rate PI controller training component.');
addTrainingBanner(mdl, ...
    'REFERENCED TRAINING COMPONENT - pitch-rate tracking PI; illustrative gains only');

addInport(mdl, 'q_cmd_limited', 1, [30 100 60 120], 'double', 'deg/s');
addInport(mdl, 'q_rate_feedback', 2, [30 235 60 255], 'double', 'deg/s');
errorPath = [mdl '/Pitch Rate Error'];
add_block('simulink/Math Operations/Sum', errorPath, ...
    'Inputs', '+-', 'IconShape', 'round', ...
    'Position', [145 120 180 165], ...
    'BackgroundColor', 'yellow');
controllerPath = [mdl '/Pitch Rate PI'];
add_block('simulink/Ports & Subsystems/Subsystem', controllerPath, ...
    'Position', [250 105 410 185], ...
    'BackgroundColor', 'lightBlue');
buildPIControllerSubsystem(controllerPath, 'q_error_deg_s', 'actuator_demand_deg');
addOutport(mdl, 'actuator_demand_deg', 1, [535 120 565 140], 'double', 'deg');
addOutport(mdl, 'q_tracking_error', 2, [535 235 565 255], 'double', 'deg/s');

addNamedLine(mdl, 'q_cmd_limited/1', 'Pitch Rate Error/1', ...
    'q_cmd_limited', true);
addNamedLine(mdl, 'q_rate_feedback/1', 'Pitch Rate Error/2', ...
    'q_rate_feedback', true);
addNamedLine(mdl, 'Pitch Rate Error/1', 'Pitch Rate PI/1', ...
    'q_tracking_error', true);
addNamedLine(mdl, 'Pitch Rate PI/1', 'actuator_demand_deg/1', ...
    'actuator_demand_deg', true);
addNamedLine(mdl, 'Pitch Rate Error/1', 'q_tracking_error/1', '', false);

saveGeneratedModel(mdl, modelsDir);
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);
end


function createActuatorCommandReference(modelsDir)
mdl = 'ActuatorCommandRef';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 2.0);
set_param(mdl, 'Description', ...
    'Referenced actuator-command magnitude saturation training component.');
addTrainingBanner(mdl, ...
    'REFERENCED TRAINING COMPONENT - actuator command magnitude protection');

addInport(mdl, 'actuator_demand_deg', 1, [30 135 60 155], 'double', 'deg');
satPath = [mdl '/Actuator Magnitude Limit'];
add_block('simulink/Discontinuities/Saturation', satPath, ...
    'UpperLimit', 'actuator_limit_deg', ...
    'LowerLimit', '-actuator_limit_deg', ...
    'Position', [180 115 275 170], ...
    'BackgroundColor', 'lightBlue');
absPath = [mdl '/Absolute Demand'];
add_block('simulink/Math Operations/Abs', absPath, ...
    'Position', [175 230 220 260], ...
    'BackgroundColor', 'yellow');
limitPath = [mdl '/Actuator Limit'];
add_block('simulink/Sources/Constant', limitPath, ...
    'Value', 'actuator_limit_deg', ...
    'OutDataTypeStr', 'double', ...
    'SampleTime', 'Sample_time', ...
    'Position', [175 300 240 330], ...
    'BackgroundColor', 'yellow');
activePath = [mdl '/Saturation Active'];
add_block('simulink/Logic and Bit Operations/Relational Operator', activePath, ...
    'Operator', '>', ...
    'Position', [315 245 360 285], ...
    'BackgroundColor', 'yellow');
addOutport(mdl, 'actuator_cmd_deg', 1, [455 125 485 145], 'double', 'deg');
addOutport(mdl, 'actuator_limit_active', 2, [455 255 485 275], 'boolean', '1');

addNamedLine(mdl, 'actuator_demand_deg/1', 'Actuator Magnitude Limit/1', ...
    'actuator_demand_deg', true);
addNamedLine(mdl, 'Actuator Magnitude Limit/1', 'actuator_cmd_deg/1', ...
    'actuator_cmd_deg', true);
addNamedLine(mdl, 'actuator_demand_deg/1', 'Absolute Demand/1', '', false);
addNamedLine(mdl, 'Absolute Demand/1', 'Saturation Active/1', '', false);
addNamedLine(mdl, 'Actuator Limit/1', 'Saturation Active/2', '', false);
addNamedLine(mdl, 'Saturation Active/1', 'actuator_limit_active/1', ...
    'actuator_limit_active', true);

saveGeneratedModel(mdl, modelsDir);
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);
end


function createReferencedArchitecture(modelsDir)
mdl = 'ReferencedFlightControlArchitecture';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 4.0);
set_param(mdl, 'Description', [ ...
    'Referenced-model flight-control architecture training example with ' ...
    'a typed FlightControlBus and explicit interface routing.']);
architectureBanner = addTrainingBanner(mdl, [ ...
    'ILLUSTRATIVE REFERENCED FLIGHT-CONTROL ARCHITECTURE - NOT PRODUCTION\n' ...
    'Typed bus -> Sensor Processing -> Pitch Rate Limiter -> Pitch Controller -> Actuator Command']);
architectureBanner.Position = [280 35 1220 80];

% Representative sensor and mode interface.
addInport(mdl, 'q_rate', 1, [30 105 60 125], 'double', 'deg/s');
addInport(mdl, 'pitch_angle', 2, [30 150 60 170], 'double', 'deg');
addInport(mdl, 'mach', 3, [30 195 60 215], 'double', '1');
addInport(mdl, 'air_data_valid', 4, [30 240 60 260], 'boolean', '1');
addInport(mdl, 'mode', 5, [30 285 60 305], 'uint8', '1');
addInport(mdl, 'q_cmd_in', 6, [690 475 720 495], 'double', 'deg/s');

busCreator = [mdl '/Create FlightControlBus'];
add_block('simulink/Signal Routing/Bus Creator', busCreator, ...
    'Inputs', '5', ...
    'OutDataTypeStr', 'Bus: FlightControlBus', ...
    'Position', [140 95 190 315], ...
    'BackgroundColor', 'lightBlue');

sensorRef = [mdl '/Sensor Processing'];
addModelReference(sensorRef, 'SensorProcessingRef', [280 135 480 250]);
selector = [mdl '/Controller Bus Inputs'];
add_block('simulink/Signal Routing/Bus Selector', selector, ...
    'OutputSignals', 'q_rate,air_data_valid,mode', ...
    'Position', [580 300 640 450], ...
    'BackgroundColor', 'lightBlue');
normalPath = [mdl '/Mode Is NORMAL'];
add_block('simulink/Logic and Bit Operations/Compare To Constant', normalPath, ...
    'relop', '==', ...
    'const', 'normal_mode_code', ...
    'Position', [680 400 810 440], ...
    'BackgroundColor', 'yellow');

limiterRef = [mdl '/Pitch Rate Limiter'];
addModelReference(limiterRef, 'PitchRateLimiter', [850 450 1050 585]);
controllerRef = [mdl '/Pitch Controller'];
addModelReference(controllerRef, 'PitchControllerRef', [1150 450 1340 585]);
actuatorRef = [mdl '/Actuator Command'];
addModelReference(actuatorRef, 'ActuatorCommandRef', [1450 450 1640 585]);

addBusOutport(mdl, 'processed_flight_data', 1, [1450 175 1480 195]);
addOutport(mdl, 'actuator_cmd_deg', 2, [1730 475 1760 495], 'double', 'deg');
addOutport(mdl, 'limiter_active', 3, [1100 620 1130 640], 'boolean', '1');
addOutport(mdl, 'actuator_limit_active', 4, [1680 620 1710 640], 'boolean', '1');
addOutport(mdl, 'q_tracking_error', 5, [1390 620 1420 640], 'double', 'deg/s');

inputNames = {'q_rate','pitch_angle','mach','air_data_valid','mode'};
for idx = 1:numel(inputNames)
    addNamedLine(mdl, sprintf('%s/1', inputNames{idx}), ...
        sprintf('Create FlightControlBus/%d', idx), inputNames{idx}, true);
end
addNamedLine(mdl, 'Create FlightControlBus/1', 'Sensor Processing/1', ...
    'raw_flight_control_bus', true);
addNamedLine(mdl, 'Sensor Processing/1', 'Controller Bus Inputs/1', ...
    'processed_flight_control_bus', true);
addNamedLine(mdl, 'Sensor Processing/1', 'processed_flight_data/1', '', false);
addNamedLine(mdl, 'Controller Bus Inputs/3', 'Mode Is NORMAL/1', 'mode', false);
addNamedLine(mdl, 'q_cmd_in/1', 'Pitch Rate Limiter/1', 'q_cmd_in', true);
addNamedLine(mdl, 'Mode Is NORMAL/1', 'Pitch Rate Limiter/2', ...
    'normal_mode', true);
addNamedLine(mdl, 'Controller Bus Inputs/2', 'Pitch Rate Limiter/3', ...
    'air_data_valid', true);
addNamedLine(mdl, 'Pitch Rate Limiter/1', 'Pitch Controller/1', ...
    'q_cmd_limited', true);
addNamedLine(mdl, 'Controller Bus Inputs/1', 'Pitch Controller/2', ...
    'q_rate_feedback', true);
addNamedLine(mdl, 'Pitch Controller/1', 'Actuator Command/1', ...
    'actuator_demand_deg', true);
addNamedLine(mdl, 'Actuator Command/1', 'actuator_cmd_deg/1', ...
    'actuator_cmd_deg', true);
addNamedLine(mdl, 'Pitch Rate Limiter/2', 'limiter_active/1', ...
    'limiter_active', true);
addNamedLine(mdl, 'Actuator Command/2', 'actuator_limit_active/1', ...
    'actuator_limit_active', true);
addNamedLine(mdl, 'Pitch Controller/2', 'q_tracking_error/1', ...
    'q_tracking_error', true);

set_param(mdl, ...
    'ShowPortDataTypes', 'off', ...
    'ShowLineDimensions', 'off', ...
    'ShowPortUnits', 'off');
lineHandles = find_system(mdl, 'FindAll', 'on', ...
    'SearchDepth', 1, 'Type', 'line');
Simulink.BlockDiagram.routeLine(lineHandles);

% Preserve the three-lane reading order after autorouting: processed bus
% at the top, the command path through the middle, and status outputs
% beneath their producers.  The custom logging names remain on source
% ports even where redundant visible line labels are suppressed.
setOutputLineRoute([mdl '/Controller Bus Inputs'], 1, ...
    [645 325; 1100 325; 1100 550; 1135 550], false);
setOutputLineRoute([mdl '/Controller Bus Inputs'], 2, ...
    [645 375; 665 375; 665 565; 835 565], false);
setOutputLineRoute([mdl '/Controller Bus Inputs'], 3, ...
    [645 425; 655 425; 655 420; 665 420], false);
setOutputLineRoute([mdl '/Mode Is NORMAL'], 1, ...
    [815 420; 825 420; 825 520; 835 520], true);
setOutputLineRoute([mdl '/q_cmd_in'], 1, ...
    [725 485; 805 485; 805 475; 835 475], true);
setOutputLineRoute([mdl '/Pitch Rate Limiter'], 1, ...
    [1055 485; 1135 485], true);
setOutputLineRoute([mdl '/Pitch Rate Limiter'], 2, ...
    [1055 555; 1085 555; 1085 630], true);
setOutputLineRoute([mdl '/Pitch Controller'], 1, ...
    [1345 485; 1380 485; 1380 520; 1435 520], true);
setOutputLineRoute([mdl '/Pitch Controller'], 2, ...
    [1345 550; 1375 550; 1375 630], true);
setOutputLineRoute([mdl '/Actuator Command'], 1, ...
    [1645 485; 1715 485], true);
setOutputLineRoute([mdl '/Actuator Command'], 2, ...
    [1645 550; 1665 550; 1665 630], true);

addTrainingNote(mdl, [280 675 1500 715], [ ...
    'Interface review focus: named model-reference boundaries, a single ' ...
    'FlightControlBus definition, explicit scalar extraction, controlled ' ...
    'parameters, units, data types, and 50 Hz execution.']);

saveGeneratedModel(mdl, modelsDir);
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);
end


function createPitchRateLimiterHarness(modelsDir)
mdl = 'PitchRateLimiter_Harness';
startFreshModel(mdl, modelsDir);
configureDiscreteModel(mdl, 2.0);
set_param(mdl, 'Description', [ ...
    'Standalone executable harness for PitchRateLimiter. It is used when ' ...
    'Simulink Test is unavailable and remains useful for scripted tests.']);
addTrainingBanner(mdl, [ ...
    'EXECUTABLE TRAINING HARNESS - From Workspace stimuli -> referenced unit -> captured outputs\n' ...
    'Stimulus variables: q_cmd_test, normal_mode_test, input_valid_test']);

% Save benign deterministic placeholders in the model workspace so the
% harness can update immediately after generation. The executable test
% suite overrides all three variables for each actual assessment run.
placeholderTime = [0; 0.02];
modelWorkspace = get_param(mdl, 'ModelWorkspace');
assignin(modelWorkspace, 'q_cmd_test', ...
    timeseries([0; 0], placeholderTime, 'Name', 'q_cmd_test'));
assignin(modelWorkspace, 'normal_mode_test', ...
    timeseries(logical([1; 1]), placeholderTime, 'Name', 'normal_mode_test'));
assignin(modelWorkspace, 'input_valid_test', ...
    timeseries(logical([1; 1]), placeholderTime, 'Name', 'input_valid_test'));

addFromWorkspace(mdl, 'q_cmd_test', 'q_cmd_test', [35 105 145 135]);
addFromWorkspace(mdl, 'normal_mode_test', 'normal_mode_test', [35 180 145 210]);
addFromWorkspace(mdl, 'input_valid_test', 'input_valid_test', [35 255 145 285]);

unitPath = [mdl '/Unit Under Test - PitchRateLimiter'];
addModelReference(unitPath, 'PitchRateLimiter', [245 115 455 285]);

addToWorkspace(mdl, 'Capture q_cmd_out', 'q_cmd_out_harness', [565 135 690 165]);
addToWorkspace(mdl, 'Capture limiter_active', 'limiter_active_harness', [565 235 690 265]);

addNamedLine(mdl, 'q_cmd_test/1', 'Unit Under Test - PitchRateLimiter/1', ...
    'q_cmd_test', true);
addNamedLine(mdl, 'normal_mode_test/1', 'Unit Under Test - PitchRateLimiter/2', ...
    'normal_mode_test', true);
addNamedLine(mdl, 'input_valid_test/1', 'Unit Under Test - PitchRateLimiter/3', ...
    'input_valid_test', true);
addNamedLine(mdl, 'Unit Under Test - PitchRateLimiter/1', 'Capture q_cmd_out/1', ...
    'q_cmd_out', true);
addNamedLine(mdl, 'Unit Under Test - PitchRateLimiter/2', ...
    'Capture limiter_active/1', 'limiter_active', true);
addTrainingNote(mdl, [160 355 585 410], [ ...
    'Pass/fail criteria belong in run_pitch_rate_limiter_tests.m. ' ...
    'The harness contains no hidden assessment logic.']);

saveGeneratedModel(mdl, modelsDir);
set_param(mdl, 'SimulationCommand', 'update');
save_system(mdl);
end


function configureDiscreteModel(mdl, stopTime)
set_param(mdl, ...
    'DataDictionary', 'FCS_Data.sldd', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'Sample_time', ...
    'StartTime', '0.0', ...
    'StopTime', num2str(stopTime), ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'SaveTime', 'on', ...
    'TimeSaveName', 'tout', ...
    'SaveOutput', 'on', ...
    'OutputSaveName', 'yout', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'MaxIdLength', '63');
end


function startFreshModel(mdl, modelsDir)
if bdIsLoaded(mdl)
    if strcmp(get_param(mdl, 'Dirty'), 'on')
        error('TrainingModels:DirtyGeneratedModel', ...
            'Refusing to discard unsaved changes in generated model %s.', mdl);
    end
    close_system(mdl, 0);
end
existingModel = fullfile(modelsDir, [mdl '.slx']);
if isfile(existingModel)
    delete(existingModel);
end
new_system(mdl, 'Model');
set_param(mdl, ...
    'ScreenColor', 'white', ...
    'ShowPortDataTypes', 'on', ...
    'ShowLineDimensions', 'on', ...
    'ShowStorageClass', 'off');
end


function saveGeneratedModel(mdl, modelsDir)
modelPath = fullfile(modelsDir, [mdl '.slx']);
save_system(mdl, modelPath);
end


function addInport(sys, name, port, position, dataType, unit)
path = [sys '/' name];
add_block('simulink/Sources/In1', path, ...
    'Port', num2str(port), ...
    'OutDataTypeStr', dataType, ...
    'Unit', unit, ...
    'SampleTime', 'Sample_time', ...
    'Position', position, ...
    'BackgroundColor', 'lightBlue');
end


function addOutport(sys, name, port, position, dataType, unit)
path = [sys '/' name];
add_block('simulink/Sinks/Out1', path, ...
    'Port', num2str(port), ...
    'OutDataTypeStr', dataType, ...
    'Unit', unit, ...
    'Position', position, ...
    'BackgroundColor', 'green');
end


function addBusInport(sys, name, port, position)
path = [sys '/' name];
add_block('simulink/Sources/In1', path, ...
    'Port', num2str(port), ...
    'OutDataTypeStr', 'Bus: FlightControlBus', ...
    'SampleTime', 'Sample_time', ...
    'Position', position, ...
    'BackgroundColor', 'lightBlue');
end


function addBusOutport(sys, name, port, position)
path = [sys '/' name];
add_block('simulink/Sinks/Out1', path, ...
    'Port', num2str(port), ...
    'OutDataTypeStr', 'Bus: FlightControlBus', ...
    'Position', position, ...
    'BackgroundColor', 'green');
end


function addFromWorkspace(sys, blockName, variableName, position)
path = [sys '/' blockName];
add_block('simulink/Sources/From Workspace', path, ...
    'VariableName', variableName, ...
    'SampleTime', 'Sample_time', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', position, ...
    'BackgroundColor', 'lightBlue');
end


function addToWorkspace(sys, blockName, variableName, position)
path = [sys '/' blockName];
add_block('simulink/Sinks/To Workspace', path, ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'Position', position, ...
    'BackgroundColor', 'green');
end


function addModelReference(path, referencedModel, position)
add_block('simulink/Ports & Subsystems/Model', path, ...
    'ModelName', referencedModel, ...
    'Position', position, ...
    'BackgroundColor', 'lightBlue');
set_param(path, 'SimulationMode', 'Normal');
set_param(path, 'Description', sprintf( ...
    'Model reference to %s.slx (illustrative training component).', ...
    referencedModel));
end


function lineHandle = addNamedLine(sys, source, destination, signalName, logSignal)
lineHandle = add_line(sys, source, destination, 'autorouting', 'on');
sourcePort = get_param(lineHandle, 'SrcPortHandle');
sourceBlock = get_param(sourcePort, 'Parent');
sourceBlockType = get_param(sourceBlock, 'BlockType');
% Bus Selector outputs inherit their element names and reject relabeling.
if ~isempty(signalName) && ~strcmp(sourceBlockType, 'BusSelector')
    set_param(lineHandle, 'Name', signalName);
end
if logSignal
    % R2023b stores signal-logging configuration on the source port rather
    % than on the line handle returned by add_line.
    set_param(sourcePort, 'DataLogging', 'on');
    if ~isempty(signalName)
        set_param(sourcePort, ...
            'DataLoggingNameMode', 'Custom', ...
            'DataLoggingName', signalName);
    end
end
end


function setOutputLineRoute(blockPath, outputIndex, points, hideName)
ports = get_param(blockPath, 'PortHandles');
lineHandle = get_param(ports.Outport(outputIndex), 'Line');
assert(lineHandle > 0, 'Training:MissingLine', ...
    'Missing expected output line: %s/%d', blockPath, outputIndex);
set_param(lineHandle, 'Points', points);
if hideName
    set_param(lineHandle, 'Name', '');
end
end


function note = addTrainingBanner(sys, text)
text = strrep(text, '\n', newline);
note = Simulink.Annotation(sys, text);
note.Position = [25 15 950 60];
note.FontSize = 12;
note.FontWeight = 'bold';
note.ForegroundColor = 'blue';
note.BackgroundColor = 'white';
end


function addTrainingNote(sys, position, text)
note = Simulink.Annotation(sys, text);
note.Position = position;
note.FontSize = 10;
note.ForegroundColor = 'black';
note.BackgroundColor = 'white';
end


function verifyDictionaryEntries(dictionaryPath, requiredEntries)
dictionary = Simulink.data.dictionary.open(char(dictionaryPath));
dictionaryCleanup = onCleanup(@()close(dictionary)); %#ok<NASGU>
section = getSection(dictionary, 'Design Data');
missing = strings(0, 1);
for idx = 1:numel(requiredEntries)
    try
        getEntry(section, char(requiredEntries(idx)));
    catch
        missing(end+1,1) = requiredEntries(idx); %#ok<AGROW>
    end
end
if ~isempty(missing)
    error('TrainingModels:MissingDictionaryEntries', ...
        'FCS_Data.sldd is missing required Design Data entries: %s', ...
        strjoin(missing, ', '));
end
end


function restoreTemporaryPaths(dataDir, dataWasAdded)
if dataWasAdded && contains(path, dataDir)
    rmpath(dataDir);
end
end
