function summary = validate_training_project(projectRoot)
%VALIDATE_TRAINING_PROJECT Compile every model and verify expected artifacts.

if nargin < 1 || strlength(string(projectRoot)) == 0
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end
projectRoot = char(projectRoot);
modelsDir = fullfile(projectRoot,'models');
dataDir = fullfile(projectRoot,'data');
resultsDir = fullfile(projectRoot,'results');
reportsDir = fullfile(projectRoot,'reports');
screensDir = fullfile(projectRoot,'screenshots');
addpath(modelsDir,dataDir,fullfile(projectRoot,'scripts'));

modelNames = { ...
    'PitchRateLimiter', ...
    'AircraftFeedbackControlLoop', ...
    'AutopilotModeLogic', ...
    'SensorProcessingRef', ...
    'PitchControllerRef', ...
    'ActuatorCommandRef', ...
    'ReferencedFlightControlArchitecture', ...
    'PitchRateLimiter_Harness'};

modelStatus = false(size(modelNames));
modelWarnings = strings(size(modelNames));
modelWarningIds = strings(size(modelNames));
acceptedLicenseWarnings = false(size(modelNames));
for index = 1:numel(modelNames)
    modelName = modelNames{index};
    modelFile = fullfile(modelsDir,[modelName '.slx']);
    assert(isfile(modelFile),'Missing model: %s',modelFile);
    openedHere = localOpenExpectedModel(modelName, modelFile);
    modelGuard = onCleanup(@() localCloseOpenedModel( ...
        modelName, openedHere)); %#ok<NASGU>
    modelReferenceBlocks = find_system(modelName, ...
        'LookUnderMasks','all', ...
        'FollowLinks','on', ...
        'BlockType','ModelReference');
    for blockIndex = 1:numel(modelReferenceBlocks)
        simulationMode = get_param(modelReferenceBlocks{blockIndex}, ...
            'SimulationMode');
        assert(strcmpi(simulationMode,'Normal'), ...
            'Training:UnexpectedModelReferenceMode', ...
            'Model block %s is saved in %s mode; expected Normal.', ...
            modelReferenceBlocks{blockIndex}, simulationMode);
    end
    lastwarn('');
    set_param(modelName,'SimulationCommand','update');
    [warningText,warningId] = lastwarn;
    warningText = regexprep(warningText, ...
        '<a href="[^"]+">([^<]+)</a>', '$1');
    modelWarnings(index) = string(warningText);
    modelWarningIds(index) = string(warningId);
    acceptedLicenseWarnings(index) = ...
        strcmp(warningId, ...
            'Simulink:modelReference:MdlRefNotAvailForLicense') && ...
        contains(warningText, ...
            'Model blocks using Accelerator mode are not supported with this license') && ...
        ~isempty(modelReferenceBlocks);
    assert(strlength(modelWarnings(index)) == 0 || ...
        acceptedLicenseWarnings(index), ...
        'Model update produced an unexpected warning for %s [%s]: %s', ...
        modelName, warningId, modelWarnings(index));
    if ~openedHere
        assert(strcmpi(get_param(modelName,'Dirty'),'off'), ...
            'Training:ValidationChangedOpenModel', ...
            ['Validation changed the already-open model %s. It has been ' ...
             'left open and unsaved so the learner can inspect it.'], ...
            modelName);
    end
    modelStatus(index) = true;
    clear modelGuard;
end

dictionaryPath = fullfile(dataDir,'FCS_Data.sldd');
assert(isfile(dictionaryPath),'Missing data dictionary: %s',dictionaryPath);
dictionary = Simulink.data.dictionary.open(dictionaryPath);
dictionaryGuard = onCleanup(@() close(dictionary)); %#ok<NASGU>
section = getSection(dictionary,'Design Data');
requiredEntries = {'Sample_time','q_limit_normal','pitch_Kp','pitch_Ki', ...
    'sensor_filter_alpha','FlightControlBus'};
for index = 1:numel(requiredEntries)
    getEntry(section,requiredEntries{index});
end

resultsCsv = fullfile(resultsDir,'PitchRateLimiter_TestResults.csv');
assert(isfile(resultsCsv),'Missing executed test CSV: %s',resultsCsv);
testTable = readtable(resultsCsv,'TextType','string','Delimiter',',');
assert(height(testTable) == 19, 'Training:UnexpectedTestCount', ...
    'Expected exactly 19 PitchRateLimiter assessments; found %d.', ...
    height(testTable));
passVariable = find(strcmpi(testTable.Properties.VariableNames,'Passed'),1);
assert(~isempty(passVariable),'Test CSV does not contain a Passed column.');
passValues = localValidatePassValues(testTable{:,passVariable}, 19);
assert(all(passValues),'One or more PitchRateLimiter test assessments failed.');

requiredArtifacts = { ...
    fullfile(reportsDir,'PitchRateLimiter_TestReport.html'), ...
    fullfile(screensDir,'pitch_rate_limiter.png'), ...
    fullfile(screensDir,'aircraft_feedback_loop.png'), ...
    fullfile(screensDir,'pitch_controller_subsystem.png'), ...
    fullfile(screensDir,'AircraftFeedback_ActuatorDynamics.png'), ...
    fullfile(screensDir,'AircraftFeedback_LongitudinalPlant.png'), ...
    fullfile(screensDir,'AircraftFeedback_SensorProcessingLag.png'), ...
    fullfile(screensDir,'AutopilotModeLogic_Model.png'), ...
    fullfile(screensDir,'autopilot_mode_logic.png'), ...
    fullfile(screensDir,'referenced_architecture.png'), ...
    fullfile(screensDir,'SensorProcessingRef_Model.png'), ...
    fullfile(screensDir,'PitchControllerRef_Model.png'), ...
    fullfile(screensDir,'PitchControllerRef_PitchRatePI.png'), ...
    fullfile(screensDir,'ActuatorCommandRef_Model.png'), ...
    fullfile(screensDir,'data_dictionary_bus.png'), ...
    fullfile(screensDir,'pitch_rate_limiter_harness.png'), ...
    fullfile(screensDir,'pitch_rate_limiter_test_results.png'), ...
    fullfile(screensDir,'command_tracking_plot.png'), ...
    fullfile(screensDir,'callback_workflow.png'), ...
    fullfile(screensDir,'pitch_rate_limiter_logic.png'), ...
    fullfile(screensDir,'pitch_rate_limiter_test_report.png'), ...
    fullfile(screensDir,'evidence_chain_summary.png'), ...
    fullfile(dataDir,'SimulationDataInspector', ...
        'AircraftFeedbackControlLoop_Onboarding_View.mldatx'), ...
    fullfile(resultsDir,'SimulationDataInspector', ...
        'AircraftFeedbackControlLoop_Onboarding_Session.mldatx')};
for index = 1:numel(requiredArtifacts)
    assert(isfile(requiredArtifacts{index}),'Missing exported artifact: %s',requiredArtifacts{index});
end

summary = struct( ...
    'validatedAt', datetime('now','TimeZone','local'), ...
    'modelNames', {modelNames}, ...
    'modelUpdatePassed', modelStatus, ...
    'modelWarnings', modelWarnings, ...
    'modelWarningIds', modelWarningIds, ...
    'acceptedLicenseWarnings', acceptedLicenseWarnings, ...
    'testAssessments', height(testTable), ...
    'testAssessmentsPassed', sum(passValues), ...
    'dictionaryEntriesResolved', {requiredEntries}, ...
    'requiredArtifacts', {requiredArtifacts}, ...
    'passed', true);

reportPath = fullfile(resultsDir,'validation_summary.txt');
fileId = fopen(reportPath,'w');
assert(fileId ~= -1,'Could not create validation summary: %s',reportPath);
fileGuard = onCleanup(@() fclose(fileId)); %#ok<NASGU>
fprintf(fileId,'Aviation Controls Simulink Training validation\n');
fprintf(fileId,'Generated: %s\n',datestr(now,31));
fprintf(fileId,'MATLAB: %s\n',version);
fprintf(fileId,'Models updated: %d/%d\n',sum(modelStatus),numel(modelStatus));
for index = 1:numel(modelNames)
    if acceptedLicenseWarnings(index)
        fprintf(fileId,['- %s: PASS — accepted R2023b Student-license ' ...
            'Model-block fallback message; every saved ModelReference ' ...
            'SimulationMode was asserted Normal before update\n'], ...
            modelNames{index});
    else
        fprintf(fileId,'- %s: PASS\n',modelNames{index});
    end
end
fprintf(fileId,['Accepted license messages: %d (only exact ' ...
    'Simulink:modelReference:MdlRefNotAvailForLicense messages)\n'], ...
    nnz(acceptedLicenseWarnings));
fprintf(fileId,'PitchRateLimiter assessments: %d/%d PASS\n',sum(passValues),height(testTable));
fprintf(fileId,['Assessment scope: retained CSV observed by validator; ' ...
    'the validator does not rerun the limiter simulation.\n']);
fprintf(fileId,'Dictionary entries resolved: %d/%d\n',numel(requiredEntries),numel(requiredEntries));
fprintf(fileId,'Required exported artifacts: %d/%d present\n',numel(requiredArtifacts),numel(requiredArtifacts));
fprintf(fileId,['Artifact scope: required-file presence observed; freshness ' ...
    'and content hashes are not established by this validator.\n']);
fprintf(fileId,'HIL executed: NO\n');
fprintf(fileId,'Jenkins executed: NO\n');
fprintf(fileId,'Overall: PASS\n');
end

function openedHere = localOpenExpectedModel(modelName, modelFile)
openedHere = false;
if bdIsLoaded(modelName)
    localAssertExpectedModelFile(modelName, modelFile);
    assert(strcmpi(get_param(modelName,'Dirty'),'off'), ...
        'Training:DirtyOpenModel', ...
        ['Refusing to validate dirty model %s. Save or discard the learner ' ...
         'changes explicitly, then run validation again.'], modelName);
    return;
end

load_system(modelFile);
openedHere = true;
try
    localAssertExpectedModelFile(modelName, modelFile);
catch openError
    try
        close_system(modelName,0);
    catch closeError
        openError = addCause(openError, closeError);
    end
    rethrow(openError);
end
end

function localCloseOpenedModel(modelName, openedHere)
if openedHere && bdIsLoaded(modelName)
    close_system(modelName,0);
end
end

function localAssertExpectedModelFile(modelName, expectedFile)
actualFile = get_param(modelName,'FileName');
assert(~isempty(actualFile), 'Training:UnresolvedModelFile', ...
    'Loaded model %s does not report a source file.', modelName);
expectedPath = localCanonicalPath(expectedFile);
actualPath = localCanonicalPath(actualFile);
assert(strcmpi(actualPath, expectedPath), ...
    'Training:UnexpectedModelFile', ...
    ['Model name %s is already bound to a different file.\n' ...
     'Expected: %s\nLoaded: %s'], ...
    modelName, expectedPath, actualPath);
end

function canonicalPath = localCanonicalPath(filePath)
[resolved, attributes] = fileattrib(filePath);
assert(resolved, 'Training:UnresolvedPath', ...
    'Could not resolve file path: %s', filePath);
canonicalPath = strrep(attributes.Name, '/', filesep);
end

function passValues = localValidatePassValues(rawValues, expectedCount)
if islogical(rawValues)
    passValues = rawValues;
    validValues = true(size(rawValues));
elseif isnumeric(rawValues)
    validValues = isfinite(rawValues) & ...
        (rawValues == 0 | rawValues == 1);
    passValues = rawValues == 1;
elseif isstring(rawValues) || iscell(rawValues) || ...
        ischar(rawValues) || iscategorical(rawValues)
    normalized = lower(strtrim(string(rawValues)));
    validValues = ismember(normalized, ...
        ["true", "false", "pass", "fail", "1", "0"]);
    passValues = ismember(normalized, ["true", "pass", "1"]);
else
    error('Training:MalformedPassColumn', ...
        'Unsupported Passed-column type: %s', class(rawValues));
end

passValues = passValues(:);
validValues = validValues(:);
assert(numel(passValues) == expectedCount, ...
    'Training:MalformedPassColumn', ...
    'Passed column has %d values; expected %d.', ...
    numel(passValues), expectedCount);
assert(all(validValues), 'Training:MalformedPassColumn', ...
    ['Passed column contains blank, NaN, or unrecognized values. ' ...
     'Use true/false, pass/fail, or 1/0.']);
end
